### ISSUE TITLE
Add a documentation of the PARAVER trace format

### ISSUE THREAD

**Issue by mickours** [bsc-performance-tools/paraver-kernel#2]
PARAVER traces format is not documented (as far as I know but I may be mistaking) and it hard to build third-party tools to convert, build, or modify them.

It would be great to have a full specification of the format with a versioning of this format.

**Comment by executre** [comment]
You can find the trace format documentation at tools website:
[https://tools.bsc.es/tools_manuals](https://tools.bsc.es/tools_manuals)
Explicitly you can refer to "Trace Generation Manual". It's an old document but totally valid.
